AWSTemplateFormatVersion: '2010-09-09'
Description: Install and configure elasticsearch on ubuntu server

Parameters:
  EnvName:
    Default: dev
    Description: Write Environment Name
    Type: String
    MinLength: '1'
    MaxLength: '10'
  ServiceName:
    Default: elasticsearch
    Description: Write Service Name
    Type: String
    MinLength: '1'
    MaxLength: '10'

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
        Count: '1'
    Metadata:
      AWS::CloudFormation::Authentication:
        S3AccessCreds:
          type: "S3"
          roleName: "ec2-generic"
      AWS::CloudFormation::Init:
        configSets:
          InstallAndRun:
            - Install
            - Configure
        Install:
          packages:
            apt:
             openjdk-11-jre-headless: []
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Join 
                - ''
                - - |
                    [main]
                  - stack=
                  - !Ref 'AWS::StackId'
                  - |+

                  - region=
                  - !Ref 'AWS::Region'
                  - |+

              mode: '000644'
              owner: root
              group: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Join 
                - ''
                - - |
                    [cfn-auto-reloader-hook]
                  - |
                    triggers=post.update
                  - >
                    path=Resources.WebServerInstance.Metadata.AWS::CloudFormation::Init
                  - 'action=/opt/aws/bin/cfn-init -v '
                  - '         --stack '
                  - !Ref 'AWS::StackName'
                  - '         --resource WebServerInstance '
                  - '         --configsets InstallAndRun '
                  - '         --region '
                  - !Ref 'AWS::Region'
                  - |+

                  - |
                    runas=root
              mode: '000644'
              owner: root
              group: root
            /lib/systemd/system/cfn-hup.service:
              content:
                Fn::Join:
                - ''
                - - "[Unit]\n"
                  - "Description=cfn-hup daemon\n\n"
                  - "[Service]\n"
                  - 'Type=simple

                    '
                  - 'ExecStart=/usr/local/bin/cfn-hup

                    '
                  - "Restart=always\n\n"
                  - "[Install]\n"
                  - WantedBy=multi-user.target
            /home/ubuntu/elasticsearch_restore.sh:
              mode: '000775'
              owner: ubuntu
              group: ubuntu
              source: "https://hf-devops.s3.ap-south-1.amazonaws.com/ps/configs/elasticsearch/elasticsearch_restore.sh"
              authentication: "S3AccessCreds"
          services:
            sysvinit:
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
          commands:
            01enable_cfn_hup:
              command: systemctl enable cfn-hup.service
            02start_cfn_hup:
              command: systemctl start cfn-hup.service
        Configure:
          commands:
            03SetIstTimeZone:
              command: timedatectl set-timezone Asia/Kolkata
            04SetServerHardeningProperties:
              command: !Join 
                - ''
                - - echo 'fs.file-max = 500000' >> /etc/sysctl.conf; 
                  - ''
                  - echo '*	soft	nproc	65535' >> /etc/security/limits.conf;
                  - ''
                  - echo '*	hard	nproc	65535' >> /etc/security/limits.conf;
                  - ''
                  - echo '*	soft	nofile	500000' >> /etc/security/limits.conf;
                  - ''
                  - echo '*	hard	nofile	500000' >> /etc/security/limits.conf
            05SetHostname:
              command: !Join 
                - ''
                - - hostnamectl set-hostname 
                  - ' '
                  - !Ref EnvName
                  - '-'
                  - !Ref ServiceName
            06InstallElasticsearch:
              command: 'sudo apt -y install elasticsearch'
            07StartElasticsearchService:
              command: "systemctl start elasticsearch; systemctl enable elasticsearch"
            08ReplaceElasticsearchServerIP:
              command: sed -i "s/IP/$(hostname -I | xargs)/g" elasticsearch_restore.sh
              cwd: "/home/ubuntu"
    Properties:
      ImageId: "ami-08795883c7b4b7140"
      InstanceType: t4g.medium
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: "20"
            DeleteOnTermination: true
            VolumeType: "gp3"
      KeyName: devops-access
      IamInstanceProfile: 
        Ref: MyInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          SubnetId: "subnet-03f1f0ddXXXXXXXX"
          GroupSet:
            - sg-05b5dccc1a1954dc4
      UserData:
        Fn::Base64:
          Fn::Join:
          - ''
          - - "#!/bin/bash -xe\n"
            - 'wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
            
              '
            - 'sudo apt-get -y install apt-transport-https
            
              '
            - 'echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
            
              '
            - 'sudo apt-get update -y

              '
            - 'sudo apt-get -y install python3-pip

              '
            - 'mkdir -p /opt/aws/

              '
            - 'sudo pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz

              '
            - 'sudo ln -s /usr/local/init/ubuntu/cfn-hup /etc/init.d/cfn-hup

              '
            - "/usr/local/bin/cfn-init -v "
            - "         --stack "
            - Ref: AWS::StackName
            - "         --resource EC2Instance "
            - "         --configsets InstallAndRun "
            - "         --region "
            - Ref: AWS::Region
            - "\n"
            - "/usr/local/bin/cfn-signal -e $? "
            - "         --stack "
            - Ref: AWS::StackName
            - "         --resource EC2Instance "
            - "         --region "
            - Ref: AWS::Region
            - "\n"
      Tags:
        - Key: Name
          Value: !Join [ '-', [!Ref EnvName, !Ref ServiceName] ]
  
  ElasticSearchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH Access
      VpcId: "vpc-0a5304a0XXXXXXXX"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
          Description: "ssh_access_open_for_all"
        - IpProtocol: tcp
          FromPort: '9200'
          ToPort: '9200'
          CidrIp: 0.0.0.0/0
          Description: "elasticsearch_access_open_for_all"
      Tags:
        - Key: Name
          Value: !Join [ '-', [!Ref EnvName, !Ref ServiceName, 'sg'] ]

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - "ec2-generic"

Outputs:
  ElasticsearchPvtIP:
    Description: Elasticsearch Server Private IP
    Value: !GetAtt EC2Instance.PrivateIp